name: Release Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository_owner == 'oku-ui'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install


      - name: Add Tag
        run: ./scripts/add-tag.sh
